export const jobArr = {
    "status": true,
    "message": "Success",
    "data": [
        {
            "views": 7,
            "companyName": "AM DEV STUDIO",
            "companyId": "",
            "companySlug": "",
            "companyLogo": "",
            "companyVerified": false,
            "featuredBenefits": "",
            "skills": [
                "LeadGeneration",
                "DealClosing&Negotiation",
                "IT/SoftwareBasicUnderstanding",
                "FluentEnglish"
            ],
            "category": {
                "_id": "6499f660d7d3bec5b121e02f",
                "name": "Marketing & Sales",
                "description": "Explore exciting opportunities in Marketing & Sales! This category is perfect for professionals who excel in creating impactful strategies and driving business growth. From digital marketing to brand management, find your perfect role and make a measurable impact in this dynamic field. Join us and unleash your marketing and sales expertise!",
                "isActive": true,
                "postCounts": 1092,
                "createdBy": "63dea7b3fa1a27096f4ea85a",
                "createdAt": "2023-06-26T20:34:40.106Z",
                "updatedAt": "2026-09-17T12:59:09.761Z",
                "__v": 0,
                "id": "6499f660d7d3bec5b121e02f"
            },
            "experience": "0 to 2 Year",
            "position": "Mid-Level",
            "noOfPositions": 10,
            "payRangeStart": 0,
            "payRangeEnd": 0,
            "salaryCurrency": "PKR",
            "jobFeseability": "Remote",
            "jobType": "Freelance",
            "_id": "6aabe41d26e6517afc03fe78",
            "designation": "IT Sales Executive",
            "desc": "\u003Cp\u003EWe&nbsp;are&nbsp;looking&nbsp;for&nbsp;a&nbsp;results-driven&nbsp;\u003Cstrong\u003EBusiness&nbsp;Development&nbsp;Executive\u003C/strong\u003E&nbsp;to&nbsp;join&nbsp;our&nbsp;team.&nbsp;Your&nbsp;main&nbsp;focus&nbsp;will&nbsp;be&nbsp;acquiring&nbsp;new&nbsp;clients&nbsp;and&nbsp;bringing&nbsp;sales&nbsp;for&nbsp;our&nbsp;software&nbsp;development,&nbsp;web&nbsp;development,&nbsp;and&nbsp;digital&nbsp;services.\u003C/p\u003E\u003Cp\u003E\u003Cstrong\u003EKey&nbsp;Responsibilities:\u003C/strong\u003E\u003C/p\u003E\u003Cul\u003E\u003Cli\u003EFind&nbsp;and&nbsp;reach&nbsp;out&nbsp;to&nbsp;potential&nbsp;international&nbsp;and&nbsp;local&nbsp;clients&nbsp;through&nbsp;cold&nbsp;outreach,&nbsp;LinkedIn,&nbsp;and&nbsp;freelancing&nbsp;platforms&nbsp;(Upwork/Fiverr).\u003C/li\u003E\u003Cli\u003EPitch&nbsp;software&nbsp;services,&nbsp;draft&nbsp;custom&nbsp;proposals,&nbsp;and&nbsp;negotiate&nbsp;project&nbsp;deals.\u003C/li\u003E\u003Cli\u003ECommunicate&nbsp;with&nbsp;leads,&nbsp;gather&nbsp;project&nbsp;requirements,&nbsp;and&nbsp;close&nbsp;sales.\u003C/li\u003E\u003Cli\u003EMaintain&nbsp;strong&nbsp;relationships&nbsp;with&nbsp;existing&nbsp;clients&nbsp;for&nbsp;repeat&nbsp;business.\u003C/li\u003E\u003C/ul\u003E\u003Cp\u003E\u003Cstrong\u003ERequirements:\u003C/strong\u003E\u003C/p\u003E\u003Cul\u003E\u003Cli\u003EProven&nbsp;experience&nbsp;in&nbsp;IT&nbsp;sales,&nbsp;lead&nbsp;generation,&nbsp;or&nbsp;proposal&nbsp;writing.\u003C/li\u003E\u003Cli\u003EStrong&nbsp;written&nbsp;and&nbsp;spoken&nbsp;English&nbsp;communication&nbsp;skills.\u003C/li\u003E\u003Cli\u003EFamiliarity&nbsp;with&nbsp;Upwork,&nbsp;Fiverr,&nbsp;LinkedIn&nbsp;Sales&nbsp;Navigator,&nbsp;or&nbsp;cold&nbsp;emailing&nbsp;strategies.\u003C/li\u003E\u003Cli\u003ESolid&nbsp;negotiation&nbsp;and&nbsp;client&nbsp;handling&nbsp;skills.\u003C/li\u003E\u003C/ul\u003E\u003Cp\u003E\u003C/p\u003E",
            "isVerified": true,
            "isHidden": false,
            "hashTags": [
                "#ITSalesExecutive",
                "#salesexecutive"
            ],
            "country": "Pakistan",
            "city": "Karachi",
            "district": "",
            "locationLabel": "",
            "officeLocationLabel": "",
            "isActive": true,
            "createdAt": "2026-09-17T12:59:09.663Z",
            "updatedAt": "2026-09-18T14:34:39.775Z",
            "gender": "Male",
            "applyPhone": 3122767819,
            "matchLockats": true,
            "sponsored": false,
            "appliedBy": 0,
            "status": "active",
            "isAcceptingApplications": true,
            "screeningQuestionsEnabled": false,
            "screeningQuestions": [],
            "googleMapsUrl": "",
            "latitude": null,
            "longitude": null,
            "user": {
                "userId": "694bc55e97c24dfd52a282ca",
                "firstName": "Muhammad Ayan ",
                "lastName": "Muhammad Waqar ",
                "userName": "muhammadayansheikh786",
                "profilePic": "https://cdn.hiringmine.com/profile/image/1775287381658-muhammadayansheikh786-profilePicture.png",
                "city": "Karachi",
                "country": "Pakistan",
                "jobTitle": "Frontend Developer , Website Developer, JavaScript developer "
            },
            "collaborators": [
                {
                    "_id": "owner-6aabe41d26e6517afc03fe78",
                    "collaboratorId": null,
                    "userId": "694bc55e97c24dfd52a282ca",
                    "userName": "muhammadayansheikh786",
                    "firstName": "Muhammad Ayan ",
                    "lastName": "Muhammad Waqar ",
                    "fullName": "Muhammad Ayan  Muhammad Waqar",
                    "profilePic": "https://cdn.hiringmine.com/profile/image/1775287381658-muhammadayansheikh786-profilePicture.png",
                    "city": "Karachi",
                    "country": "Pakistan",
                    "location": "Karachi, Pakistan",
                    "jobTitle": "Frontend Developer , Website Developer, JavaScript developer ",
                    "role": "owner",
                    "status": "active"
                }
            ],
            "recruiters": [
                {
                    "_id": "owner-6aabe41d26e6517afc03fe78",
                    "collaboratorId": null,
                    "userId": "694bc55e97c24dfd52a282ca",
                    "userName": "muhammadayansheikh786",
                    "firstName": "Muhammad Ayan ",
                    "lastName": "Muhammad Waqar ",
                    "fullName": "Muhammad Ayan  Muhammad Waqar",
                    "profilePic": "profile/image/1775287381658-muhammadayansheikh786-profilePicture.png",
                    "city": "Karachi",
                    "country": "Pakistan",
                    "location": "Karachi, Pakistan",
                    "jobTitle": "Frontend Developer , Website Developer, JavaScript developer ",
                    "role": "owner",
                    "status": "active"
                }
            ],
            "recruiterTeam": [
                {
                    "_id": "owner-6aabe41d26e6517afc03fe78",
                    "collaboratorId": null,
                    "userId": "694bc55e97c24dfd52a282ca",
                    "userName": "muhammadayansheikh786",
                    "firstName": "Muhammad Ayan ",
                    "lastName": "Muhammad Waqar ",
                    "fullName": "Muhammad Ayan  Muhammad Waqar",
                    "profilePic": "profile/image/1775287381658-muhammadayansheikh786-profilePicture.png",
                    "city": "Karachi",
                    "country": "Pakistan",
                    "location": "Karachi, Pakistan",
                    "jobTitle": "Frontend Developer , Website Developer, JavaScript developer ",
                    "role": "owner",
                    "status": "active"
                }
            ],
            "publicRecruiters": [
                {
                    "_id": "owner-6aabe41d26e6517afc03fe78",
                    "collaboratorId": null,
                    "userId": "694bc55e97c24dfd52a282ca",
                    "userName": "muhammadayansheikh786",
                    "firstName": "Muhammad Ayan ",
                    "lastName": "Muhammad Waqar ",
                    "fullName": "Muhammad Ayan  Muhammad Waqar",
                    "profilePic": "profile/image/1775287381658-muhammadayansheikh786-profilePicture.png",
                    "city": "Karachi",
                    "country": "Pakistan",
                    "location": "Karachi, Pakistan",
                    "jobTitle": "Frontend Developer , Website Developer, JavaScript developer ",
                    "role": "owner",
                    "status": "active"
                }
            ],
            "recruiterCount": 1
        },
        {
            "views": 4,
            "companyName": "",
            "companyId": "",
            "companySlug": "",
            "companyLogo": "",
            "companyVerified": false,
            "featuredBenefits": "",
            "skills": [
                "Blender",
                "3DModeling",
                "Unity",
                "UVMapping",
                "Texturing",
                "PolygonOptimization",
                "GameAssetCreation",
                "PBRWorkflow",
                "3DDesign",
                "Real-timeRendering"
            ],
            "category": {
                "_id": "6499f691d7d3bec5b121e037",
                "name": "Information Tech",
                "description": "Join the cutting-edge field of Information Tech! This category is perfect for tech enthusiasts who excel in areas such as software engineering, cybersecurity, and data analysis. Whether you're a programmer, a network administrator, or a data scientist, find exciting opportunities to contribute to technological advancements. Join us and shape the future of IT!",
                "isActive": true,
                "postCounts": 161,
                "createdBy": "63dea7b3fa1a27096f4ea85a",
                "createdAt": "2023-06-26T20:35:29.119Z",
                "updatedAt": "2026-09-17T12:17:28.635Z",
                "__v": 0,
                "id": "6499f691d7d3bec5b121e037"
            },
            "experience": "1 to 10 Year",
            "position": "Senior-Level",
            "noOfPositions": 1,
            "payRangeStart": 0,
            "payRangeEnd": 0,
            "salaryCurrency": "USD",
            "jobFeseability": "Remote",
            "jobType": "Contract",
            "_id": "6aabda5826e6517afc03f2cc",
            "designation": "Blender 3D Modeler for Unity Game Development",
            "desc": "\u003Cp\u003E\u003Cstrong\u003EJob&nbsp;Title:&nbsp;Blender&nbsp;3D&nbsp;Modeler&nbsp;for&nbsp;Unity&nbsp;Game&nbsp;Development\u003C/strong\u003E\u003C/p\u003E\u003Cp\u003E\u003C/p\u003E\u003Cp\u003E\u003Cstrong\u003EJob&nbsp;Description:\u003C/strong\u003E\u003C/p\u003E\u003Cp\u003EWe&nbsp;are&nbsp;seeking&nbsp;a&nbsp;skilled&nbsp;Blender&nbsp;3D&nbsp;Modeler&nbsp;to&nbsp;create&nbsp;high-quality&nbsp;3D&nbsp;assets&nbsp;for&nbsp;Unity&nbsp;game&nbsp;development&nbsp;projects.&nbsp;The&nbsp;ideal&nbsp;candidate&nbsp;will&nbsp;have&nbsp;a&nbsp;strong&nbsp;understanding&nbsp;of&nbsp;3D&nbsp;modeling&nbsp;techniques&nbsp;and&nbsp;experience&nbsp;optimizing&nbsp;models&nbsp;for&nbsp;real-time&nbsp;game&nbsp;engines.\u003C/p\u003E\u003Cp\u003E\u003C/p\u003E\u003Cp\u003E\u003Cstrong\u003EKey&nbsp;Responsibilities:\u003C/strong\u003E\u003C/p\u003E\u003Cp\u003ECreate&nbsp;detailed&nbsp;3D&nbsp;models&nbsp;using&nbsp;Blender&nbsp;for&nbsp;Unity&nbsp;game&nbsp;projects\u003C/p\u003E\u003Cp\u003EDevelop&nbsp;game-ready&nbsp;assets&nbsp;including&nbsp;characters,&nbsp;environments,&nbsp;props,&nbsp;and&nbsp;objects\u003C/p\u003E\u003Cp\u003EOptimize&nbsp;3D&nbsp;models&nbsp;for&nbsp;performance&nbsp;in&nbsp;Unity&nbsp;engine\u003C/p\u003E\u003Cp\u003EEnsure&nbsp;proper&nbsp;UV&nbsp;mapping&nbsp;and&nbsp;texturing&nbsp;for&nbsp;all&nbsp;models\u003C/p\u003E\u003Cp\u003ECollaborate&nbsp;with&nbsp;game&nbsp;developers&nbsp;to&nbsp;meet&nbsp;project&nbsp;requirements\u003C/p\u003E\u003Cp\u003EMaintain&nbsp;consistent&nbsp;art&nbsp;style&nbsp;throughout&nbsp;the&nbsp;project\u003C/p\u003E\u003Cp\u003EExport&nbsp;models&nbsp;in&nbsp;appropriate&nbsp;formats&nbsp;compatible&nbsp;with&nbsp;Unity\u003C/p\u003E\u003Cp\u003E\u003C/p\u003E\u003Cp\u003E\u003Cstrong\u003ERequirements:\u003C/strong\u003E\u003C/p\u003E\u003Cp\u003EProficiency&nbsp;in&nbsp;Blender&nbsp;3D&nbsp;modeling&nbsp;software\u003C/p\u003E\u003Cp\u003EExperience&nbsp;with&nbsp;Unity&nbsp;game&nbsp;engine&nbsp;and&nbsp;asset&nbsp;integration\u003C/p\u003E\u003Cp\u003EStrong&nbsp;understanding&nbsp;of&nbsp;polygon&nbsp;optimization&nbsp;and&nbsp;LOD&nbsp;creation\u003C/p\u003E\u003Cp\u003EKnowledge&nbsp;of&nbsp;UV&nbsp;mapping&nbsp;and&nbsp;texturing&nbsp;workflows\u003C/p\u003E\u003Cp\u003EPortfolio&nbsp;demonstrating&nbsp;previous&nbsp;3D&nbsp;modeling&nbsp;work\u003C/p\u003E\u003Cp\u003EAbility&nbsp;to&nbsp;work&nbsp;independently&nbsp;and&nbsp;meet&nbsp;deadlines\u003C/p\u003E\u003Cp\u003E\u003C/p\u003E\u003Cp\u003E\u003Cstrong\u003EPreferred&nbsp;Skills:\u003C/strong\u003E\u003C/p\u003E\u003Cp\u003EExperience&nbsp;with&nbsp;PBR&nbsp;texturing&nbsp;workflows\u003C/p\u003E\u003Cp\u003EKnowledge&nbsp;of&nbsp;rigging&nbsp;and&nbsp;animation&nbsp;basics\u003C/p\u003E\u003Cp\u003EFamiliarity&nbsp;with&nbsp;game&nbsp;development&nbsp;pipelines\u003C/p\u003E\u003Cp\u003EUnderstanding&nbsp;of&nbsp;mobile&nbsp;game&nbsp;optimization\u003C/p\u003E",
            "isVerified": true,
            "isHidden": false,
            "hashTags": [
                "#Blender",
                "#3DModeling",
                "#Unity",
                "#GameDevelopment",
                "#3DArtist",
                "#GameDesign",
                "#UnityEngine",
                "#3DAssets",
                "#Modeling",
                "#GameArt",
                "#DigitalArt",
                "#GameDev"
            ],
            "country": "France",
            "city": "Paris",
            "district": "",
            "locationLabel": "",
            "officeLocationLabel": "",
            "isActive": true,
            "createdAt": "2026-09-17T12:17:28.529Z",
            "updatedAt": "2026-09-18T11:43:26.258Z",
            "gender": "",
            "matchLockats": false,
            "sponsored": false,
            "appliedBy": 0,
            "status": "active",
            "isAcceptingApplications": true,
            "screeningQuestionsEnabled": false,
            "screeningQuestions": [],
            "googleMapsUrl": "",
            "latitude": null,
            "longitude": null,
            "user": {
                "userId": "677ebc6117ac458625be4675",
                "firstName": "Afaq",
                "lastName": "A.",
                "userName": "afaq",
                "profilePic": "https://cdn.hiringmine.com/profile/image/1742289489968-afaq-profilePicture.png",
                "city": "Karachi",
                "country": "PK",
                "jobTitle": "Full-Stack Developer"
            },
            "collaborators": [
                {
                    "_id": "owner-6aabda5826e6517afc03f2cc",
                    "collaboratorId": null,
                    "userId": "677ebc6117ac458625be4675",
                    "userName": "afaq",
                    "firstName": "Afaq",
                    "lastName": "A.",
                    "fullName": "Afaq A.",
                    "profilePic": "https://cdn.hiringmine.com/profile/image/1742289489968-afaq-profilePicture.png",
                    "city": "Karachi",
                    "country": "PK",
                    "location": "Karachi, PK",
                    "jobTitle": "Full-Stack Developer",
                    "role": "owner",
                    "status": "active"
                }
            ],
            "recruiters": [
                {
                    "_id": "owner-6aabda5826e6517afc03f2cc",
                    "collaboratorId": null,
                    "userId": "677ebc6117ac458625be4675",
                    "userName": "afaq",
                    "firstName": "Afaq",
                    "lastName": "A.",
                    "fullName": "Afaq A.",
                    "profilePic": "profile/image/1742289489968-afaq-profilePicture.png",
                    "city": "Karachi",
                    "country": "PK",
                    "location": "Karachi, PK",
                    "jobTitle": "Full-Stack Developer",
                    "role": "owner",
                    "status": "active"
                }
            ],
            "recruiterTeam": [
                {
                    "_id": "owner-6aabda5826e6517afc03f2cc",
                    "collaboratorId": null,
                    "userId": "677ebc6117ac458625be4675",
                    "userName": "afaq",
                    "firstName": "Afaq",
                    "lastName": "A.",
                    "fullName": "Afaq A.",
                    "profilePic": "profile/image/1742289489968-afaq-profilePicture.png",
                    "city": "Karachi",
                    "country": "PK",
                    "location": "Karachi, PK",
                    "jobTitle": "Full-Stack Developer",
                    "role": "owner",
                    "status": "active"
                }
            ],
            "publicRecruiters": [
                {
                    "_id": "owner-6aabda5826e6517afc03f2cc",
                    "collaboratorId": null,
                    "userId": "677ebc6117ac458625be4675",
                    "userName": "afaq",
                    "firstName": "Afaq",
                    "lastName": "A.",
                    "fullName": "Afaq A.",
                    "profilePic": "profile/image/1742289489968-afaq-profilePicture.png",
                    "city": "Karachi",
                    "country": "PK",
                    "location": "Karachi, PK",
                    "jobTitle": "Full-Stack Developer",
                    "role": "owner",
                    "status": "active"
                }
            ],
            "recruiterCount": 1
        },
        {
            "views": 94,
            "companyName": "HACSONS ",
            "companyId": "",
            "companySlug": "",
            "companyLogo": "",
            "companyVerified": false,
            "featuredBenefits": "",
            "skills": [
                "Inventorymanagement/stockcontrolAttentiontodetailOrganizingandlabellingsystemsBasiccomputerskills(Excelorinventorysoftware)Physicalstamina(lifting",
                "movingstock)TimemanagementBasiccommunication(coordinatingwithsales/purchaseteam)"
            ],
            "category": {
                "_id": "6499f685d7d3bec5b121e035",
                "name": "Management",
                "description": "Lead the way in Management! This category is dedicated to professionals who possess exceptional leadership skills and thrive in overseeing teams and driving strategic initiatives. From project management to operations management, find your next managerial role and make a significant impact on organizational success. Join us and take your management career to new heights!",
                "isActive": true,
                "postCounts": 150,
                "createdBy": "63dea7b3fa1a27096f4ea85a",
                "createdAt": "2023-06-26T20:35:17.074Z",
                "updatedAt": "2026-09-16T12:34:18.873Z",
                "__v": 0,
                "id": "6499f685d7d3bec5b121e035"
            },
            "experience": "0 to 2 Year",
            "position": "Mid-Level",
            "noOfPositions": 2,
            "payRangeStart": 40000,
            "payRangeEnd": 49000,
            "salaryCurrency": "PKR",
            "jobFeseability": "Onsite",
            "jobType": "Full-Time",
            "_id": "6aaa8cca26e6517afc032a1c",
            "designation": " Warehouse Inventory & Officer",
            "desc": "\u003Cp\u003ECompany:&nbsp;HAC&nbsp;&amp;&nbsp;Son\u003C/p\u003E\u003Cp\u003ELocation:&nbsp;Karachi\u003C/p\u003E\u003Cp\u003E\u003C/p\u003E\u003Cp\u003EResponsibilities:\u003C/p\u003E\u003Cp\u003E\u003C/p\u003E\u003Cp\u003EManage&nbsp;day-to-day&nbsp;stock&nbsp;in&nbsp;and&nbsp;out\u003C/p\u003E\u003Cp\u003EOrganize&nbsp;warehouse&nbsp;layout&nbsp;and&nbsp;settings\u003C/p\u003E\u003Cp\u003ELabel&nbsp;items&nbsp;clearly&nbsp;for&nbsp;easy&nbsp;identification\u003C/p\u003E\u003Cp\u003EMaintain&nbsp;accurate&nbsp;inventory&nbsp;records\u003C/p\u003E\u003Cp\u003ERequirements:\u003C/p\u003E\u003Cp\u003E\u003C/p\u003E\u003Cp\u003EPrior&nbsp;warehouse/stock&nbsp;experience&nbsp;preferred\u003C/p\u003E\u003Cp\u003EOrganized,&nbsp;detail-oriented,&nbsp;and&nbsp;reliable\u003C/p\u003E\u003Cp\u003EBasic&nbsp;computer&nbsp;skills&nbsp;for&nbsp;record-keeping\u003C/p\u003E\u003Cp\u003EHow&nbsp;to&nbsp;Apply:\u003C/p\u003E\u003Cp\u003ESend&nbsp;your&nbsp;CV&nbsp;to&nbsp;[03333822410]&nbsp;with&nbsp;the&nbsp;subject&nbsp;line&nbsp;&quot;Warehouse&nbsp;Stock&nbsp;Officer&nbsp;Application.&quot;\u003C/p\u003E",
            "isVerified": true,
            "isHidden": false,
            "hashTags": [
                "#WEARHOUSE"
            ],
            "country": "",
            "city": "",
            "district": "",
            "locationLabel": "",
            "officeLocationLabel": "",
            "isActive": true,
            "createdAt": "2026-09-16T12:34:18.768Z",
            "updatedAt": "2026-09-18T15:50:09.522Z",
            "gender": "Male",
            "applyPhone": 923333822410,
            "matchLockats": false,
            "sponsored": false,
            "appliedBy": 2,
            "status": "active",
            "isAcceptingApplications": true,
            "screeningQuestionsEnabled": false,
            "screeningQuestions": [],
            "googleMapsUrl": "",
            "latitude": null,
            "longitude": null,
            "user": {
                "userId": "6a92915e9057757c0da2df98",
                "firstName": "Hac&son",
                "lastName": "Burhanuddin",
                "userName": "hacsonburhanuddin",
                "profilePic": "https://lh3.googleusercontent.com/a/ACg8ocLWFrEdwa5-iIppLOIhUkDprL3zQDn20b79HGhkc_BD-vig14Y7=s96-c"
            },
            "collaborators": [
                {
                    "_id": "owner-6aaa8cca26e6517afc032a1c",
                    "collaboratorId": null,
                    "userId": "6a92915e9057757c0da2df98",
                    "userName": "hacsonburhanuddin",
                    "firstName": "Hac&son",
                    "lastName": "Burhanuddin",
                    "fullName": "Hac&son Burhanuddin",
                    "profilePic": "https://lh3.googleusercontent.com/a/ACg8ocLWFrEdwa5-iIppLOIhUkDprL3zQDn20b79HGhkc_BD-vig14Y7=s96-c",
                    "city": "",
                    "country": "",
                    "location": "",
                    "jobTitle": "",
                    "role": "owner",
                    "status": "active"
                }
            ],
            "recruiters": [
                {
                    "_id": "owner-6aaa8cca26e6517afc032a1c",
                    "collaboratorId": null,
                    "userId": "6a92915e9057757c0da2df98",
                    "userName": "hacsonburhanuddin",
                    "firstName": "Hac&son",
                    "lastName": "Burhanuddin",
                    "fullName": "Hac&son Burhanuddin",
                    "profilePic": "https://lh3.googleusercontent.com/a/ACg8ocLWFrEdwa5-iIppLOIhUkDprL3zQDn20b79HGhkc_BD-vig14Y7=s96-c",
                    "city": "",
                    "country": "",
                    "location": "",
                    "jobTitle": "",
                    "role": "owner",
                    "status": "active"
                }
            ],
            "recruiterTeam": [
                {
                    "_id": "owner-6aaa8cca26e6517afc032a1c",
                    "collaboratorId": null,
                    "userId": "6a92915e9057757c0da2df98",
                    "userName": "hacsonburhanuddin",
                    "firstName": "Hac&son",
                    "lastName": "Burhanuddin",
                    "fullName": "Hac&son Burhanuddin",
                    "profilePic": "https://lh3.googleusercontent.com/a/ACg8ocLWFrEdwa5-iIppLOIhUkDprL3zQDn20b79HGhkc_BD-vig14Y7=s96-c",
                    "city": "",
                    "country": "",
                    "location": "",
                    "jobTitle": "",
                    "role": "owner",
                    "status": "active"
                }
            ],
            "publicRecruiters": [
                {
                    "_id": "owner-6aaa8cca26e6517afc032a1c",
                    "collaboratorId": null,
                    "userId": "6a92915e9057757c0da2df98",
                    "userName": "hacsonburhanuddin",
                    "firstName": "Hac&son",
                    "lastName": "Burhanuddin",
                    "fullName": "Hac&son Burhanuddin",
                    "profilePic": "https://lh3.googleusercontent.com/a/ACg8ocLWFrEdwa5-iIppLOIhUkDprL3zQDn20b79HGhkc_BD-vig14Y7=s96-c",
                    "city": "",
                    "country": "",
                    "location": "",
                    "jobTitle": "",
                    "role": "owner",
                    "status": "active"
                }
            ],
            "recruiterCount": 1
        },
        {
            "views": 185,
            "companyName": "Pharmacy & Beauty/Cosmetics Brand",
            "companyId": "",
            "companySlug": "",
            "companyLogo": "",
            "companyVerified": false,
            "featuredBenefits": "nothing",
            "skills": [
                "SocialMediaManagement",
                "VideoEditing",
                "ContentCreation",
                "GraphicDesign",
                "CommunityManagement",
                "InfluencerMarketing",
                "Instagram",
                "Facebook",
                "TikTok",
                "Canva",
                "AdobePremiere",
                "CommunicationSkills"
            ],
            "category": {
                "_id": "655bb610bad423d5da61fb1c",
                "name": "Content Creation and Editing",
                "description": "Dive into the world of content creation and editing – where skilled professionals shape impactful multimedia across diverse industries.",
                "isActive": true,
                "postCounts": 121,
                "createdBy": "651edd68cff4b74735bb3fd4",
                "createdAt": "2023-11-20T19:40:00.141Z",
                "updatedAt": "2026-09-15T11:40:08.323Z",
                "__v": 0,
                "id": "655bb610bad423d5da61fb1c"
            },
            "experience": "1 to 2 Year",
            "position": "Mid-Level",
            "noOfPositions": 0,
            "payRangeStart": 0,
            "payRangeEnd": 0,
            "salaryCurrency": "PKR",
            "jobFeseability": "Remote",
            "jobType": "Contract",
            "_id": "6aa92e9826e6517afc02051c",
            "designation": "Social Media Manager",
            "desc": "\u003Cp\u003E\u003Cstrong\u003EWe&#39;re&nbsp;Hiring&nbsp;—&nbsp;Social&nbsp;Media&nbsp;Manager\u003C/strong\u003E\u003C/p\u003E\u003Cp\u003E\u003C/p\u003E\u003Cp\u003EWe&#39;re&nbsp;looking&nbsp;for&nbsp;a&nbsp;creative&nbsp;\u003Cstrong\u003ESocial&nbsp;Media&nbsp;Manager\u003C/strong\u003E&nbsp;for&nbsp;a&nbsp;Pharmacy&nbsp;&amp;&nbsp;Beauty/Cosmetics&nbsp;brand.\u003C/p\u003E\u003Cp\u003E\u003C/p\u003E\u003Cp\u003E\u003Cstrong\u003EWork&nbsp;Hours:\u003C/strong\u003E&nbsp;8&nbsp;Hours&nbsp;Duty\u003C/p\u003E\u003Cp\u003E\u003C/p\u003E\u003Cp\u003E\u003Cstrong\u003EMain&nbsp;Responsibilities:\u003C/strong\u003E\u003C/p\u003E\u003Cp\u003ECreate&nbsp;&amp;&nbsp;edit&nbsp;3&nbsp;short&nbsp;videos&nbsp;daily\u003C/p\u003E\u003Cp\u003EManage&nbsp;multiple&nbsp;social&nbsp;media&nbsp;platforms\u003C/p\u003E\u003Cp\u003EEngage&nbsp;with&nbsp;comments&nbsp;&amp;&nbsp;DMs\u003C/p\u003E\u003Cp\u003ECreate&nbsp;simple&nbsp;posts,&nbsp;offers&nbsp;&amp;&nbsp;banners\u003C/p\u003E\u003Cp\u003ECoordinate&nbsp;with&nbsp;influencers\u003C/p\u003E\u003Cp\u003E\u003C/p\u003E\u003Cp\u003E\u003Cstrong\u003EPreferred&nbsp;Experience:\u003C/strong\u003E\u003C/p\u003E\u003Cp\u003EBeauty/Cosmetics&nbsp;industry&nbsp;experience&nbsp;preferred\u003C/p\u003E\u003Cp\u003E\u003C/p\u003E\u003Cp\u003E\u003Cstrong\u003ETo&nbsp;Apply,&nbsp;Please&nbsp;Send:\u003C/strong\u003E\u003C/p\u003E\u003Cp\u003E1.&nbsp;Accounts&nbsp;you&nbsp;have&nbsp;managed\u003C/p\u003E\u003Cp\u003E2.&nbsp;3–5&nbsp;videos&nbsp;you&nbsp;created/edited\u003C/p\u003E\u003Cp\u003E3.&nbsp;Your&nbsp;expected&nbsp;salary\u003C/p\u003E",
            "isVerified": true,
            "isHidden": false,
            "hashTags": [
                "#SocialMediaManager",
                "#SocialMedia",
                "#ContentCreation",
                "#VideoEditing",
                "#BeautyIndustry",
                "#Cosmetics",
                "#Pharmacy",
                "#DigitalMarketing",
                "#InfluencerMarketing",
                "#SocialMediaMarketing",
                "#ContentStrategy",
                "#CommunityManagement"
            ],
            "country": "Saudi Arabia",
            "city": "Riyadh",
            "district": "",
            "locationLabel": "",
            "officeLocationLabel": "",
            "isActive": true,
            "createdAt": "2026-09-15T11:40:08.215Z",
            "updatedAt": "2026-09-18T11:28:23.155Z",
            "gender": "",
            "applyPhone": 966593578094,
            "matchLockats": false,
            "sponsored": false,
            "appliedBy": 12,
            "status": "active",
            "isAcceptingApplications": true,
            "screeningQuestionsEnabled": false,
            "screeningQuestions": [],
            "googleMapsUrl": "",
            "latitude": null,
            "longitude": null,
            "user": {
                "userId": "6aa665efca1a2845bc4d2a7c",
                "firstName": "Amirah",
                "lastName": "Bakr",
                "userName": "amirahbakr317",
                "profilePic": "https://lh3.googleusercontent.com/a/ACg8ocLQ06wFrR4j0U_h8tvB5mExnL1eUfOYkSC-Zp3pfiG3FFcMKA=s96-c"
            },
            "collaborators": [
                {
                    "_id": "owner-6aa92e9826e6517afc02051c",
                    "collaboratorId": null,
                    "userId": "6aa665efca1a2845bc4d2a7c",
                    "userName": "amirahbakr317",
                    "firstName": "Amirah",
                    "lastName": "Bakr",
                    "fullName": "Amirah Bakr",
                    "profilePic": "https://lh3.googleusercontent.com/a/ACg8ocLQ06wFrR4j0U_h8tvB5mExnL1eUfOYkSC-Zp3pfiG3FFcMKA=s96-c",
                    "city": "",
                    "country": "",
                    "location": "",
                    "jobTitle": "",
                    "role": "owner",
                    "status": "active"
                }
            ],
            "recruiters": [
                {
                    "_id": "owner-6aa92e9826e6517afc02051c",
                    "collaboratorId": null,
                    "userId": "6aa665efca1a2845bc4d2a7c",
                    "userName": "amirahbakr317",
                    "firstName": "Amirah",
                    "lastName": "Bakr",
                    "fullName": "Amirah Bakr",
                    "profilePic": "https://lh3.googleusercontent.com/a/ACg8ocLQ06wFrR4j0U_h8tvB5mExnL1eUfOYkSC-Zp3pfiG3FFcMKA=s96-c",
                    "city": "",
                    "country": "",
                    "location": "",
                    "jobTitle": "",
                    "role": "owner",
                    "status": "active"
                }
            ],
            "recruiterTeam": [
                {
                    "_id": "owner-6aa92e9826e6517afc02051c",
                    "collaboratorId": null,
                    "userId": "6aa665efca1a2845bc4d2a7c",
                    "userName": "amirahbakr317",
                    "firstName": "Amirah",
                    "lastName": "Bakr",
                    "fullName": "Amirah Bakr",
                    "profilePic": "https://lh3.googleusercontent.com/a/ACg8ocLQ06wFrR4j0U_h8tvB5mExnL1eUfOYkSC-Zp3pfiG3FFcMKA=s96-c",
                    "city": "",
                    "country": "",
                    "location": "",
                    "jobTitle": "",
                    "role": "owner",
                    "status": "active"
                }
            ],
            "publicRecruiters": [
                {
                    "_id": "owner-6aa92e9826e6517afc02051c",
                    "collaboratorId": null,
                    "userId": "6aa665efca1a2845bc4d2a7c",
                    "userName": "amirahbakr317",
                    "firstName": "Amirah",
                    "lastName": "Bakr",
                    "fullName": "Amirah Bakr",
                    "profilePic": "https://lh3.googleusercontent.com/a/ACg8ocLQ06wFrR4j0U_h8tvB5mExnL1eUfOYkSC-Zp3pfiG3FFcMKA=s96-c",
                    "city": "",
                    "country": "",
                    "location": "",
                    "jobTitle": "",
                    "role": "owner",
                    "status": "active"
                }
            ],
            "recruiterCount": 1
        },
        {
            "views": 77,
            "companyName": "Omnera ",
            "companyId": "",
            "companySlug": "",
            "companyLogo": "",
            "companyVerified": false,
            "featuredBenefits": "Nothing",
            "skills": [
                "SalesClosingHighTicket"
            ],
            "category": {
                "_id": "6499f660d7d3bec5b121e02f",
                "name": "Marketing & Sales",
                "description": "Explore exciting opportunities in Marketing & Sales! This category is perfect for professionals who excel in creating impactful strategies and driving business growth. From digital marketing to brand management, find your perfect role and make a measurable impact in this dynamic field. Join us and unleash your marketing and sales expertise!",
                "isActive": true,
                "postCounts": 1092,
                "createdBy": "63dea7b3fa1a27096f4ea85a",
                "createdAt": "2023-06-26T20:34:40.106Z",
                "updatedAt": "2026-09-17T12:59:09.761Z",
                "__v": 0
            },
            "experience": "0 to 2 Year",
            "position": "Senior-Level",
            "noOfPositions": 0,
            "payRangeStart": 0,
            "payRangeEnd": 0,
            "salaryCurrency": "PKR",
            "jobFeseability": "Remote",
            "jobType": "Freelance",
            "_id": "6aa6cd39ca1a2845bc4d6bc2",
            "designation": "B2B sales closer ",
            "desc": "\u003Cp\u003E🚨&nbsp;WE’RE&nbsp;HIRING&nbsp;—&nbsp;HIGH-TICKET&nbsp;B2B&nbsp;SALES&nbsp;CLOSER&nbsp;🚨\u003C/p\u003E\u003Cp\u003E\u003C/p\u003E\u003Cp\u003E🏢&nbsp;Company:&nbsp;Omnera&nbsp;One&nbsp;—&nbsp;Saudi&nbsp;Arabia\u003C/p\u003E\u003Cp\u003E💻&nbsp;Remote&nbsp;—&nbsp;Pakistan\u003C/p\u003E\u003Cp\u003E💰&nbsp;Commission&nbsp;on&nbsp;Every&nbsp;Closed&nbsp;Deal\u003C/p\u003E\u003Cp\u003E\u003C/p\u003E\u003Cp\u003EWe&nbsp;are&nbsp;looking&nbsp;for&nbsp;an&nbsp;experienced&nbsp;B2B&nbsp;Sales&nbsp;Closer&nbsp;who&nbsp;can&nbsp;convert&nbsp;qualified&nbsp;Pakistani&nbsp;business&nbsp;owners&nbsp;into&nbsp;paying&nbsp;clients&nbsp;for&nbsp;Saudi&nbsp;market&nbsp;entry,&nbsp;company&nbsp;formation&nbsp;and&nbsp;related&nbsp;business&nbsp;setup&nbsp;services.\u003C/p\u003E\u003Cp\u003E\u003C/p\u003E\u003Cp\u003EYou&nbsp;will&nbsp;receive&nbsp;qualified,&nbsp;pre-booked&nbsp;meetings.&nbsp;Our&nbsp;Saudi-side&nbsp;expert&nbsp;will&nbsp;also&nbsp;join&nbsp;meetings&nbsp;to&nbsp;handle&nbsp;KSA&nbsp;technical/business&nbsp;questions&nbsp;—&nbsp;your&nbsp;responsibility&nbsp;is&nbsp;to&nbsp;control&nbsp;the&nbsp;sales&nbsp;conversation&nbsp;and&nbsp;close&nbsp;the&nbsp;deal.\u003C/p\u003E\u003Cp\u003E\u003C/p\u003E\u003Cp\u003EYour&nbsp;Role\u003C/p\u003E\u003Cp\u003E\u003C/p\u003E\u003Cp\u003EConduct&nbsp;high-ticket&nbsp;B2B&nbsp;sales&nbsp;meetings\u003C/p\u003E\u003Cp\u003E\u003C/p\u003E\u003Cp\u003EUnderstand&nbsp;the&nbsp;client’s&nbsp;business&nbsp;and&nbsp;motivation&nbsp;for&nbsp;entering&nbsp;Saudi&nbsp;Arabia\u003C/p\u003E\u003Cp\u003E\u003C/p\u003E\u003Cp\u003EBuild&nbsp;trust&nbsp;and&nbsp;increase&nbsp;interest&nbsp;in&nbsp;the&nbsp;KSA&nbsp;opportunity\u003C/p\u003E\u003Cp\u003E\u003C/p\u003E\u003Cp\u003EHandle&nbsp;objections&nbsp;and&nbsp;commercial&nbsp;discussions\u003C/p\u003E\u003Cp\u003E\u003C/p\u003E\u003Cp\u003EPresent&nbsp;the&nbsp;right&nbsp;proof,&nbsp;case&nbsp;examples,&nbsp;documents&nbsp;or&nbsp;testimonials&nbsp;where&nbsp;available\u003C/p\u003E\u003Cp\u003E\u003C/p\u003E\u003Cp\u003EFollow&nbsp;up&nbsp;after&nbsp;the&nbsp;meeting&nbsp;until&nbsp;a&nbsp;clear&nbsp;decision\u003C/p\u003E\u003Cp\u003E\u003C/p\u003E\u003Cp\u003ECoordinate&nbsp;with&nbsp;the&nbsp;team&nbsp;on&nbsp;every&nbsp;active&nbsp;lead\u003C/p\u003E\u003Cp\u003E\u003C/p\u003E\u003Cp\u003EKnow&nbsp;when&nbsp;and&nbsp;what&nbsp;to&nbsp;send&nbsp;the&nbsp;prospect&nbsp;to&nbsp;move&nbsp;the&nbsp;deal&nbsp;forward\u003C/p\u003E\u003Cp\u003E\u003C/p\u003E\u003Cp\u003EPush&nbsp;qualified&nbsp;opportunities&nbsp;toward&nbsp;payment&nbsp;and&nbsp;closure\u003C/p\u003E\u003Cp\u003E\u003C/p\u003E\u003Cp\u003E\u003C/p\u003E\u003Cp\u003EWe&nbsp;Need&nbsp;Someone&nbsp;Who\u003C/p\u003E\u003Cp\u003E\u003C/p\u003E\u003Cp\u003EHas&nbsp;proven&nbsp;high-ticket&nbsp;B2B&nbsp;closing&nbsp;experience\u003C/p\u003E\u003Cp\u003E\u003C/p\u003E\u003Cp\u003ECan&nbsp;confidently&nbsp;deal&nbsp;with&nbsp;Owners,&nbsp;CEOs&nbsp;and&nbsp;Directors\u003C/p\u003E\u003Cp\u003E\u003C/p\u003E\u003Cp\u003EUnderstands&nbsp;consultative&nbsp;selling&nbsp;and&nbsp;objection&nbsp;handling\u003C/p\u003E\u003Cp\u003E\u003C/p\u003E\u003Cp\u003EKnows&nbsp;how&nbsp;to&nbsp;follow&nbsp;up&nbsp;without&nbsp;annoying&nbsp;the&nbsp;client\u003C/p\u003E\u003Cp\u003E\u003C/p\u003E\u003Cp\u003ECan&nbsp;manage&nbsp;a&nbsp;deal&nbsp;from&nbsp;meeting&nbsp;→&nbsp;follow-up&nbsp;→&nbsp;negotiation&nbsp;→&nbsp;close\u003C/p\u003E\u003Cp\u003E\u003C/p\u003E\u003Cp\u003EIs&nbsp;disciplined&nbsp;with&nbsp;pipeline&nbsp;and&nbsp;team&nbsp;communication\u003C/p\u003E\u003Cp\u003E\u003C/p\u003E\u003Cp\u003EHas&nbsp;strong&nbsp;English&nbsp;+&nbsp;Urdu&nbsp;communication\u003C/p\u003E\u003Cp\u003E\u003C/p\u003E\u003Cp\u003E\u003C/p\u003E\u003Cp\u003E\u003C/p\u003E\u003Cp\u003E\u003C/p\u003E\u003Cp\u003E📩&nbsp;Send&nbsp;your&nbsp;CV&nbsp;+&nbsp;your&nbsp;best&nbsp;closing&nbsp;result&nbsp;+&nbsp;average&nbsp;deal&nbsp;size&nbsp;+&nbsp;sales&nbsp;experience&nbsp;via&nbsp;DM.\u003C/p\u003E",
            "isVerified": true,
            "isHidden": false,
            "hashTags": [
                "#B2BsalescloserMEETINGS"
            ],
            "country": "Saudi Arabia",
            "city": "Riyadh",
            "district": "",
            "locationLabel": "",
            "officeLocationLabel": "",
            "isActive": true,
            "createdAt": "2026-09-13T16:20:09.426Z",
            "updatedAt": "2026-09-17T12:14:54.259Z",
            "gender": "",
            "applyPhone": 534606162,
            "matchLockats": true,
            "sponsored": false,
            "appliedBy": 1,
            "status": "active",
            "isAcceptingApplications": true,
            "screeningQuestionsEnabled": false,
            "screeningQuestions": [],
            "googleMapsUrl": "",
            "latitude": null,
            "longitude": null,
            "user": {
                "userId": "6aa665efca1a2845bc4d2a7c",
                "firstName": "Amirah",
                "lastName": "Bakr",
                "userName": "amirahbakr317",
                "profilePic": "https://lh3.googleusercontent.com/a/ACg8ocLQ06wFrR4j0U_h8tvB5mExnL1eUfOYkSC-Zp3pfiG3FFcMKA=s96-c"
            },
            "collaborators": [
                {
                    "_id": "owner-6aa6cd39ca1a2845bc4d6bc2",
                    "collaboratorId": null,
                    "userId": "6aa665efca1a2845bc4d2a7c",
                    "userName": "amirahbakr317",
                    "firstName": "Amirah",
                    "lastName": "Bakr",
                    "fullName": "Amirah Bakr",
                    "profilePic": "https://lh3.googleusercontent.com/a/ACg8ocLQ06wFrR4j0U_h8tvB5mExnL1eUfOYkSC-Zp3pfiG3FFcMKA=s96-c",
                    "city": "",
                    "country": "",
                    "location": "",
                    "jobTitle": "",
                    "role": "owner",
                    "status": "active"
                }
            ],
            "recruiters": [
                {
                    "_id": "owner-6aa6cd39ca1a2845bc4d6bc2",
                    "collaboratorId": null,
                    "userId": "6aa665efca1a2845bc4d2a7c",
                    "userName": "amirahbakr317",
                    "firstName": "Amirah",
                    "lastName": "Bakr",
                    "fullName": "Amirah Bakr",
                    "profilePic": "https://lh3.googleusercontent.com/a/ACg8ocLQ06wFrR4j0U_h8tvB5mExnL1eUfOYkSC-Zp3pfiG3FFcMKA=s96-c",
                    "city": "",
                    "country": "",
                    "location": "",
                    "jobTitle": "",
                    "role": "owner",
                    "status": "active"
                }
            ],
            "recruiterTeam": [
                {
                    "_id": "owner-6aa6cd39ca1a2845bc4d6bc2",
                    "collaboratorId": null,
                    "userId": "6aa665efca1a2845bc4d2a7c",
                    "userName": "amirahbakr317",
                    "firstName": "Amirah",
                    "lastName": "Bakr",
                    "fullName": "Amirah Bakr",
                    "profilePic": "https://lh3.googleusercontent.com/a/ACg8ocLQ06wFrR4j0U_h8tvB5mExnL1eUfOYkSC-Zp3pfiG3FFcMKA=s96-c",
                    "city": "",
                    "country": "",
                    "location": "",
                    "jobTitle": "",
                    "role": "owner",
                    "status": "active"
                }
            ],
            "publicRecruiters": [
                {
                    "_id": "owner-6aa6cd39ca1a2845bc4d6bc2",
                    "collaboratorId": null,
                    "userId": "6aa665efca1a2845bc4d2a7c",
                    "userName": "amirahbakr317",
                    "firstName": "Amirah",
                    "lastName": "Bakr",
                    "fullName": "Amirah Bakr",
                    "profilePic": "https://lh3.googleusercontent.com/a/ACg8ocLQ06wFrR4j0U_h8tvB5mExnL1eUfOYkSC-Zp3pfiG3FFcMKA=s96-c",
                    "city": "",
                    "country": "",
                    "location": "",
                    "jobTitle": "",
                    "role": "owner",
                    "status": "active"
                }
            ],
            "recruiterCount": 1
        }
    ],
    "count": 421,
    "paginatedData": {
        "currentPage": 1,
        "limit": 5,
        "totalDocs": 421,
        "totalPages": 85,
        "hasNextPage": true,
        "nextPage": 2
    }
}